sonar.projectKey=Insaner1980_fonecheck
sonar.organization=insaner1980
sonar.host.url=https://sonarcloud.io

sonar.exclusions=**/build/**,**/generated/**
sonar.cpd.exclusions=**/build/**,**/generated/**
sonar.secrets.excluded.file.suffixes=.webp,.ttf
sonar.scm.use.blame.algorithm=GIT_NATIVE_BLAME
