/*
 * Designed and developed by 2025 skydoves (Jaewoong Eum)
 * Modified for fonecheck: lossless receiver-aware reports. See tools/stability-analyzer/README.md.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.skydoves.compose.stability.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Task to dump composable stability information to a file.
 *
 * Similar to apiDump from binary-compatibility-validator.
 */
public abstract class StabilityDumpTask : DefaultTask() {

  /**
   * Input file containing stability information generated by the compiler.
   * Using InputFiles instead of InputFile to allow the file to not exist yet.
   */
  @get:InputFiles
  public abstract val stabilityInputFiles: ConfigurableFileCollection

  /**
   * Output directory where the stability file will be written.
   */
  @get:OutputDirectory
  public abstract val outputDir: DirectoryProperty

  /**
   * Packages to ignore.
   */
  @get:Input
  public abstract val ignoredPackages: ListProperty<String>

  /**
   * Classes to ignore.
   */
  @get:Input
  public abstract val ignoredClasses: ListProperty<String>

  /**
   * Project name (captured at configuration time for configuration cache compatibility).
   */
  @get:Input
  public abstract val projectName: Property<String>

  /**
   * Suffix to the generated stability file
   */
  @get:Input
  @get:Optional
  public abstract val stabilityFileSuffix: Property<String>

  @get:InputFiles
  @get:Optional
  @get:PathSensitive(PathSensitivity.RELATIVE)
  public abstract val stabilityConfigurationFiles: ListProperty<RegularFile>

  /**
   * When true, only unstable composables (not skippable) are included in the baseline file.
   */
  @get:Input
  public abstract val unstableOnly: Property<Boolean>

  init {
    group = "verification"
    description = "Dump composable stability information to stability file"
  }

  @TaskAction
  public fun dump() {
    val inputFile = stabilityInputFiles.files.firstOrNull { it.exists() }
    if (inputFile == null) {
      // If the file doesn't exist, it means the module has no composable functions
      // This is expected for modules like activities or utilities without composables
      logger.lifecycle("ℹ️  No composables found in :${projectName.get()}, skipping stability dump")
      return
    }

    val outputDirectory = outputDir.get().asFile
    outputDirectory.mkdirs()

    val stabilityFileName = if (stabilityFileSuffix.isPresent) {
      "${projectName.get()}-${stabilityFileSuffix.get()}"
    } else {
      projectName.get()
    }

    val outputFile = outputDirectory.resolve("$stabilityFileName.stability")
    val stabilityInfo = parseStabilityInfo(inputFile)
    val filtered = filterStabilityInfo(
      stabilityInfo,
      ignoredPackages.get(),
      ignoredClasses.get(),
    )

    val stableTypeMatchers = stabilityConfigurationFiles.getOrElse(emptyList())
      .flatMap { configRegularFile ->
        StabilityConfigParser.fromFile(configRegularFile.asFile.path).stableTypeMatchers
      }

    val resolved = applyStabilityConfiguration(filtered, stableTypeMatchers)
    val finalEntries = if (unstableOnly.get()) {
      resolved.filter { !it.skippable }
    } else {
      resolved
    }
    writeStabilityFile(outputFile, finalEntries)

    logger.lifecycle("Stability file written to: ${outputFile.absolutePath}")
  }

  private fun parseStabilityInfo(file: java.io.File): List<StabilityEntry> =
    StabilityFormat.readJson(file.readText())

  private fun filterStabilityInfo(
    entries: List<StabilityEntry>,
    ignoredPackages: List<String>,
    ignoredClasses: List<String>,
  ): List<StabilityEntry> = entries.filter { entry ->
    val packageName = entry.qualifiedName.substringBeforeLast('.', "")
    val className = entry.qualifiedName.substringAfterLast('.')

    // Filter out compiler-generated anonymous composables
    !entry.qualifiedName.contains("<anonymous>") &&
      !ignoredPackages.any { packageName.startsWith(it) } &&
      !ignoredClasses.contains(className)
  }

  private fun applyStabilityConfiguration(
    entries: List<StabilityEntry>,
    stableTypeMatchers: Collection<FqNameMatcher>,
  ): List<StabilityEntry> {
    if (stableTypeMatchers.isEmpty()) return entries

    return entries.map { entry ->
      val resolvedParams = entry.parameters.map { param ->
        if (param.stability != "STABLE" && stableTypeMatchers.any { it.matches(param.type) }) {
          param.copy(stability = "STABLE", reason = "matched by stability configuration")
        } else {
          param
        }
      }
      // Only upgrade skippability when the configuration actually rescues a parameter the compiler
      // saw as unstable, and only for a restartable composable. A non-restartable composable is
      // never skippable, and a restartable one whose parameters were already all stable yet still
      // reported skippable=false opted out via @NonSkippableComposable, so neither must be flipped
      // to skippable here (issue #184).
      val rescuedByConfiguration = resolvedParams.isNotEmpty() &&
        resolvedParams.all { it.stability == "STABLE" } &&
        entry.parameters.any { it.stability != "STABLE" }
      val resolvedSkippable = entry.skippable || (entry.restartable && rescuedByConfiguration)
      entry.copy(parameters = resolvedParams, skippable = resolvedSkippable)
    }
  }

  private fun writeStabilityFile(file: java.io.File, entries: List<StabilityEntry>) {
    if (entries.isEmpty()) {
      if (file.exists()) {
        file.delete()
        logger.lifecycle("No composables found - removed ${file.name}")
      }
      return
    }

    file.writeText(StabilityFormat.write(entries, projectName.get()))
  }
}

/**
 * Represents a composable function's stability information.
 */
internal data class StabilityEntry(
  val qualifiedName: String,
  val simpleName: String,
  val visibility: String,
  val parameters: List<ParameterInfo>,
  val returnType: String,
  val skippable: Boolean,
  val restartable: Boolean,
  val receiver: ParameterInfo? = null,
)

/**
 * Represents a parameter's stability information.
 */
internal data class ParameterInfo(
  val name: String,
  val type: String,
  val stability: String, // STABLE, UNSTABLE, RUNTIME, UNKNOWN
  val reason: String? = null,
)
