package com.skydoves.compose.stability.gradle

import kotlinx.serialization.json.*

/** Shared lossless report codec. Return type and parameter names do not select a Kotlin overload.
 * Lambda return types remain inside parameter types. Unknown/generated collisions fail closed.
 * See https://kotlinlang.org/spec/declarations.html#function-signature.
 */
internal object StabilityFormat {
  fun identity(entry: StabilityEntry): String = entry.qualifiedName +
    "(receiver=" + (entry.receiver?.type?.let(::JsonPrimitive) ?: JsonNull) +
    "; params=" + JsonArray(entry.parameters.map { JsonPrimitive(it.type) }) + ")"

  fun unique(entries: List<StabilityEntry>): Map<String, StabilityEntry> {
    val result = sortedMapOf<String, StabilityEntry>()
    entries.forEach { entry ->
      val id = identity(entry)
      require(!result.containsKey(id)) { "Duplicate canonical stability identity: $id" }
      result[id] = entry
    }
    return result
  }

  private fun JsonObject.text(key: String): String = getValue(key).jsonPrimitive.content
  private fun JsonObject.parameter(): ParameterInfo = ParameterInfo(
    text("name"), text("type"), text("stability"),
    get("reason")?.takeUnless { it is JsonNull }?.jsonPrimitive?.content,
  )

  fun readJson(text: String): List<StabilityEntry> {
    val entries = Json.parseToJsonElement(text).jsonObject.getValue("composables").jsonArray.map {
      val obj = it.jsonObject
      StabilityEntry(
        qualifiedName = obj.text("qualifiedName"), simpleName = obj.text("simpleName"),
        visibility = obj["visibility"]?.jsonPrimitive?.content ?: "public",
        parameters = obj.getValue("parameters").jsonArray.map { p -> p.jsonObject.parameter() },
        returnType = obj["returnType"]?.jsonPrimitive?.content ?: "Unit",
        skippable = obj["skippable"]?.jsonPrimitive?.boolean ?: false,
        restartable = obj["restartable"]?.jsonPrimitive?.boolean ?: true,
        receiver = obj["receiver"]?.takeUnless { r -> r is JsonNull }?.jsonObject?.parameter(),
      )
    }.filterNot { it.qualifiedName.contains("<anonymous>") }
    return unique(entries).values.toList()
  }

  private fun ParameterInfo.json(): JsonObject = buildJsonObject {
    put("name", name); put("type", type); put("stability", stability)
    reason?.let { put("reason", it) }
  }

  fun write(entries: List<StabilityEntry>, projectName: String): String = buildString {
    append("// This file was automatically generated by Compose Stability Analyzer\n")
    append("// https://github.com/skydoves/compose-stability-analyzer\n//\n")
    append("// fonecheck receiver-aware format 1\n")
    append("// Do not edit this file directly. To update it, run:\n")
    append("//   ./gradlew :$projectName:stabilityDump\n")
    unique(entries).values.forEach { entry ->
      append('\n')
      append("@Composable\n${entry.visibility} fun ${entry.qualifiedName}(")
      append(entry.parameters.joinToString(", ") { "${it.name}: ${it.type}" })
      append("): ${entry.returnType}\n")
      entry.receiver?.let { append("  receiver: ${it.json()}\n") }
      append("  skippable: ${entry.skippable}\n  restartable: ${entry.restartable}\n  params:\n")
      entry.parameters.forEach { p ->
        append("    - ${p.name}: ${p.stability}")
        p.reason?.let { append(" ($it)") }
        append('\n')
      }
    }
  }

  /** Legacy duplicates remain a list: the old producer irreversibly lost receiver information. */
  fun readBaseline(text: String): List<StabilityEntry> = text.replace("\r\n", "\n").split("@Composable\n").drop(1).map { block ->
    val lines = block.lines()
    val signature = lines.first().trim()
    val name = signature.substringAfter(" fun ").substringBefore('(')
    val start = signature.indexOf('(')
    val end = signature.lastIndexOf("): ")
    require(start >= 0 && end > start) { "Invalid baseline signature: $signature" }
    val parameterText = signature.substring(start + 1, end)
    val params = lines.filter { it.startsWith("    - ") }.map { line ->
      val value = line.removePrefix("    - ")
      val state = value.substringAfter(": ")
      ParameterInfo(value.substringBefore(": "), "", state.substringBefore(" ("),
        if (state.contains(" (")) state.substringAfter(" (").removeSuffix(")") else null)
    }
    // Parameter names delimit legacy types; commas inside generics/annotations/functions do not.
    // Names are only a decoding aid, never part of canonical identity.
    val positions = params.mapIndexed { index, p ->
      val marker = if (index == 0) "${p.name}: " else ", ${p.name}: "
      val pos = parameterText.indexOf(marker)
      require(pos >= 0) { "Missing parameter ${p.name} in $signature" }
      pos to (pos + marker.length)
    }
    require(positions.zipWithNext().all { (a, b) -> a.second <= b.first }) {
      "Ambiguous parameter boundaries in $signature"
    }
    val typed = params.mapIndexed { i, p ->
      p.copy(type = parameterText.substring(positions[i].second, positions.getOrNull(i + 1)?.first ?: parameterText.length))
    }
    val receiver = lines.firstOrNull { it.startsWith("  receiver: ") }
      ?.substringAfter("  receiver: ")?.let { Json.parseToJsonElement(it).jsonObject.parameter() }
    StabilityEntry(name, name.substringAfterLast('.'), signature.substringBefore(" fun "), typed,
      signature.substring(end + 3),
      lines.first { it.startsWith("  skippable: ") }.substringAfter(": ").toBooleanStrict(),
      lines.firstOrNull { it.startsWith("  restartable: ") }?.substringAfter(": ")?.toBooleanStrict() ?: true,
      receiver)
  }.also { entries ->
    // Receiver-bearing baselines have enough information and must never contain duplicate IDs.
    unique(if (text.contains("// fonecheck receiver-aware format 1")) entries else entries.filter { it.receiver != null })
  }

  fun referenceForComparison(current: List<StabilityEntry>, old: List<StabilityEntry>): Map<String, StabilityEntry> {
    unique(current)
    val result = sortedMapOf<String, StabilityEntry>()
    current.forEach { entry ->
      val exact = old.filter { identity(it) == identity(entry) }
      require(exact.size <= 1) { "Ambiguous legacy baseline identity: ${identity(entry)}" }
      val candidates = if (exact.isNotEmpty()) exact else old.filter {
        it.receiver == null && entry.receiver != null && it.qualifiedName == entry.qualifiedName &&
          it.parameters.map { p -> p.type } == entry.parameters.map { p -> p.type } &&
          current.none { now -> identity(now) == identity(it) }
      }
      if (candidates.isNotEmpty()) {
        if (exact.isEmpty()) {
          val destinations = current.filter { now ->
            now.receiver != null && now.qualifiedName == entry.qualifiedName &&
              now.parameters.map { it.type } == entry.parameters.map { it.type } &&
              old.none { identity(it) == identity(now) }
          }
          require(candidates.size == destinations.size) {
            "Ambiguous legacy receiver overload count for ${identity(entry)}: " +
              "${candidates.size} baseline records, ${destinations.size} current records"
          }
        }
        val states = candidates.map { Triple(it.skippable, it.restartable, it.parameters.map { p -> p.stability }) }.distinct()
        require(states.size == 1) { "Ambiguous legacy baseline stability for ${identity(entry)}; receiver information was lost upstream" }
        // Compare against the unchanged old record; never invent its receiver or use a row index as ID.
        result[identity(entry)] = candidates.first()
      }
    }
    // Preserve the old checker's regression checks across an unambiguous signature edit.
    // Never pair changed overload groups by declaration order or parameter names.
    current.filter { identity(it) !in result }.groupBy { it.qualifiedName }.forEach { (name, entries) ->
      val prior = old.filter { it.qualifiedName == name && it !in result.values }
      if (prior.isNotEmpty()) {
        require(entries.size == 1 && prior.size == 1) { "Ambiguous changed overload signatures: $name" }
        result[identity(entries.single())] = prior.single()
      }
    }
    // Keep removals visible. Indistinguishable legacy duplicates were already retained and checked above.
    old.groupBy(::identity).forEach { (id, group) ->
      if (result.values.none { it in group }) {
        require(group.size == 1) { "Ambiguous removed legacy baseline identity: $id (${group.size} records)" }
        result[id] = group.single()
      }
    }
    return result
  }
}
