package com.skydoves.compose.stability.gradle

import kotlinx.serialization.json.*
import org.junit.Assert.*
import org.junit.Test

class StabilityFormatTest {
  private fun entry(type: String = "kotlin.Int", receiver: String? = null) = StabilityEntry(
    "sensor.displayName", "displayName", "private", listOf(ParameterInfo("value", type, "STABLE")),
    "kotlin.String", true, true, receiver?.let { ParameterInfo("<this>", it, "STABLE") },
  )
  private fun json(type: String): String = buildJsonObject {
    putJsonArray("composables") {
      add(buildJsonObject {
        put("qualifiedName", "ButtonRow"); put("simpleName", "ButtonRow")
        put("skippable", true); put("restartable", true)
        putJsonArray("parameters") { add(buildJsonObject {
          put("name", "content"); put("type", type); put("stability", "STABLE")
        }) }
      })
    }
  }.toString()

  @Test fun singleEntryEndsWithExactlyOneLf() {
    val output = StabilityFormat.write(listOf(entry()), "test")
    val expected = "// This file was automatically generated by Compose Stability Analyzer\n" +
      "// https://github.com/skydoves/compose-stability-analyzer\n//\n" +
      "// fonecheck receiver-aware format 1\n" +
      "// Do not edit this file directly. To update it, run:\n" +
      "//   ./gradlew :test:stabilityDump\n\n" +
      "@Composable\nprivate fun sensor.displayName(value: kotlin.Int): kotlin.String\n" +
      "  skippable: true\n  restartable: true\n  params:\n    - value: STABLE\n"
    assertArrayEquals(expected.toByteArray(Charsets.UTF_8), output.toByteArray(Charsets.UTF_8))
    assertTrue(output.endsWith("\n"))
    assertFalse(output.endsWith("\n\n"))
  }
  @Test fun multipleEntriesKeepSeparatorsWithoutBlankLineAtEof() {
    val entries = listOf(entry(receiver="B").copy(parameters=emptyList()), entry(receiver="A"))
    val output = StabilityFormat.write(entries, "test")
    assertTrue(output.contains("    - value: STABLE\n\n@Composable\n"))
    assertTrue(output.endsWith("  params:\n"))
    assertFalse(output.endsWith("\n\n"))
    assertFalse(output.contains('\r'))
    assertEquals(StabilityFormat.unique(entries).values.toList(), StabilityFormat.readBaseline(output))
  }
  @Test fun escapedQuotesAndBackslashesSurvive() {
    val type = "@[Composable] kotlin.Function1<@[ParameterName(name = \"buttonModifier\")] androidx.compose.ui.Modifier, kotlin.Unit>"
    assertEquals(type, StabilityFormat.readJson(json(type)).single().parameters.single().type)
    val rendered = """@[Composable] androidx.compose.runtime.internal.ComposableFunction1<@[ParameterName(name = \"buttonModifier\")] androidx.compose.ui.Modifier, kotlin.Unit>"""
    val parsed = StabilityFormat.readJson(json(rendered))
    assertEquals(rendered, parsed.single().parameters.single().type)
    assertEquals(parsed, StabilityFormat.readBaseline(StabilityFormat.write(parsed, "test")))
    assertEquals("a\\b\"c\n", StabilityFormat.readJson(json("a\\b\"c\n")).single().parameters.single().type)
  }
  @Test fun nestedFunctionTypeRoundTrips() {
    val type = "kotlin.Function1<kotlin.Map<kotlin.String, kotlin.List<@[ParameterName(name = \"x\")] kotlin.Function1<kotlin.Int?, kotlin.String?>>>, kotlin.Function0<kotlin.Unit>>"
    val parsed = StabilityFormat.readJson(json(type))
    assertEquals(type, parsed.single().parameters.single().type)
    assertEquals(parsed, StabilityFormat.readBaseline(StabilityFormat.write(parsed, "test")))
  }
  @Test fun twoParameterOverloadsRemainIndependent() {
    assertEquals(2, StabilityFormat.unique(listOf(entry(), entry("kotlin.String"))).size)
  }
  @Test fun threeSensorReceiversRemainIndependent() {
    val entries = listOf("GuidedSensorCode", "GuidedSensorStatus", "SensorAccuracyCode").map {
      entry(receiver = "sensor.$it").copy(parameters = emptyList())
    }
    assertEquals(3, StabilityFormat.unique(entries).size)
    assertEquals(entries.toSet(), StabilityFormat.readBaseline(StabilityFormat.write(entries, "test")).toSet())
  }
  @Test fun receiverAndParameterOverloadsRemainIndependent() {
    assertEquals(4, StabilityFormat.unique(listOf(entry(receiver="A"), entry(receiver="B"),
      entry("kotlin.String", "A"), entry("kotlin.String", "B"))).size)
  }
  @Test fun oldJsonHasNoInventedReceiver() { assertNull(StabilityFormat.readJson(json("kotlin.Int")).single().receiver) }
  @Test fun oldBaselineWithoutRestartableIsReadable() {
    val text = "@Composable\nprivate fun sensor.displayName(value: kotlin.Int): kotlin.String\n  skippable: true\n  params:\n    - value: STABLE (primitive type)\n"
    val parsed = StabilityFormat.readBaseline(text).single()
    assertNull(parsed.receiver); assertTrue(parsed.restartable)
    assertEquals("kotlin.Int", parsed.parameters.single().type)
  }
  @Test fun regressionBelongsOnlyToChangedOverload() {
    val before = listOf(entry(), entry("kotlin.String"))
    val changed = before[0].copy(parameters=listOf(before[0].parameters[0].copy(stability="RUNTIME")))
    val diffs = compareStability(StabilityFormat.unique(listOf(changed, before[1])), StabilityFormat.unique(before), true)
    assertEquals(1, diffs.size)
    assertEquals(StabilityFormat.identity(changed), (diffs.single() as StabilityDifference.ParameterStabilityChanged).function)
  }
  @Test fun skippabilityRegressionBelongsOnlyToChangedOverload() {
    val before = listOf(entry(), entry("kotlin.String"))
    val changed = before[0].copy(skippable=false)
    val diffs = compareStability(StabilityFormat.unique(listOf(changed, before[1])), StabilityFormat.unique(before), true)
    assertEquals(listOf(StabilityDifference.SkippabilityChanged(StabilityFormat.identity(changed), true, false)), diffs)
  }
  @Test fun orderingIsDeterministic() {
    val entries = listOf(entry(), entry("String"), entry(receiver="A"))
    assertEquals(StabilityFormat.write(entries, "test"), StabilityFormat.write(entries.reversed(), "test"))
  }
  @Test fun duplicateIdentityFailsEvenWhenReturnTypeOrNamesDiffer() {
    val first = entry()
    val second = first.copy(returnType="Other", parameters=first.parameters.map { it.copy(name="renamed") })
    val error = assertThrows(IllegalArgumentException::class.java) { StabilityFormat.unique(listOf(first, second)) }
    assertTrue(error.message!!.contains("sensor.displayName(receiver=null; params=[\"kotlin.Int\"])"))
    assertThrows(IllegalArgumentException::class.java) { StabilityFormat.write(listOf(first, second), "test") }
  }
  @Test fun receiverRegressionIsDetected() {
    val old = entry(receiver="A")
    val now = old.copy(receiver=old.receiver!!.copy(stability="RUNTIME"))
    assertEquals(1, compareStability(StabilityFormat.unique(listOf(now)), StabilityFormat.unique(listOf(old)), true).size)
  }
  @Test fun changedSignatureCannotHideSkippabilityRegression() {
    val before = listOf(entry())
    val current = listOf(entry("kotlin.String").copy(skippable=false))
    assertEquals(1, compareStability(StabilityFormat.unique(current),
      StabilityFormat.referenceForComparison(current, before), true).size)
  }
  @Test fun newBaselineDuplicateWithoutReceiverFails() {
    val text = StabilityFormat.write(listOf(entry()), "test")
    assertThrows(IllegalArgumentException::class.java) {
      StabilityFormat.readBaseline(text + text.substringAfter("\n\n"))
    }
  }
  @Test fun legacyReceiverCannotBeReusedToHideAnAddedOverload() {
    assertThrows(IllegalArgumentException::class.java) {
      StabilityFormat.referenceForComparison(listOf(entry(receiver="A"), entry(receiver="B")), listOf(entry()))
    }
  }
  @Test fun ordinaryFunctionAndAddedReceiverOverloadRemainIndependent() {
    val old = entry()
    val extension = entry(receiver="A").let { it.copy(receiver=it.receiver!!.copy(stability="RUNTIME")) }
    val current = listOf(old, extension)
    val differences = compareStability(StabilityFormat.unique(current), StabilityFormat.referenceForComparison(current, listOf(old)), true)
    assertEquals(1, differences.size)
    assertEquals(StabilityFormat.identity(extension), (differences.single() as StabilityDifference.NewFunction).name)
  }
  @Test fun legacyDuplicateRowsAreRetainedAndAmbiguousStabilityFails() {
    val old = entry().copy(parameters=emptyList())
    val text = StabilityFormat.write(listOf(old), "test").replace("// fonecheck receiver-aware format 1\n", "")
    val entries = StabilityFormat.readBaseline(text + text.substringAfter("\n\n"))
    assertEquals(2, entries.size)
    val current = listOf(entry(receiver="A").copy(parameters=emptyList()), entry(receiver="B").copy(parameters=emptyList()))
    assertEquals(2, StabilityFormat.referenceForComparison(current, entries).size)
    assertThrows(IllegalArgumentException::class.java) {
      StabilityFormat.referenceForComparison(current, listOf(old, old.copy(skippable=false)))
    }
  }
}
